import { Hoodie } from '../types';

export const FALLBACK_HOODIES: Hoodie[] = [
  {
    _id: '1',
    name: 'Ghost Archive Hoodie',
    slug: 'ghost-archive-hoodie',
    brand: 'AXIS',
    description: 'A structural masterpiece. Heavyweight 450GSM cotton with a unique ghost-texture finish. Designed for the permanent collection.',
    price: 3499,
    images: [
      { url: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=1200&auto=format&fit=crop', publicId: 'p1', alt: 'Ghost Archive Hoodie Front' },
      { url: 'https://images.unsplash.com/photo-1578932750294-f5075e85f44a?w=1200&auto=format&fit=crop', publicId: 'p1-2', alt: 'Ghost Archive Hoodie Detail' },
      { url: 'https://images.unsplash.com/photo-1512353087810-25dfed2097df?w=1200&auto=format&fit=crop', publicId: 'p1-3', alt: 'Ghost Archive Hoodie Fabric' }
    ],
    category: 'streetwear',
    sizes: [{ size: 'M', stock: 12 }, { size: 'L', stock: 8 }, { size: 'XL', stock: 5 }],
    colors: [{ name: 'Bone', hex: '#E5E5E5' }, { name: 'Noir', hex: '#000000' }],
    totalStock: 25,
    featured: true,
    newArrival: false,
    viewCount: 1240,
    soldCount: 89,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '2',
    name: 'Obsidian Structure Hoodie',
    slug: 'obsidian-structure-hoodie',
    brand: 'AXIS',
    description: 'Deep obsidian black. Double-layered hood and reinforced stitching. An essential artifact for the modern minimalist.',
    price: 3899,
    images: [
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=1200&auto=format&fit=crop', publicId: 'p2', alt: 'Obsidian Structure Hoodie Front' },
      { url: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=1200&auto=format&fit=crop', publicId: 'p2-2', alt: 'Obsidian Structure Hoodie Back' },
      { url: 'https://images.unsplash.com/photo-1512353087810-25dfed2097df?w=1200&auto=format&fit=crop', publicId: 'p2-3', alt: 'Obsidian Structure Hoodie Close' }
    ],
    category: 'oversized',
    sizes: [{ size: 'S', stock: 4 }, { size: 'M', stock: 10 }, { size: 'L', stock: 2 }],
    colors: [{ name: 'Obsidian', hex: '#1A1A1A' }],
    totalStock: 16,
    featured: true,
    newArrival: true,
    viewCount: 2100,
    soldCount: 45,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '3',
    name: 'Spectral Knit Artifact',
    slug: 'spectral-knit-artifact',
    brand: 'AXIS',
    description: 'Hand-finished spectral knit. Oversized silhouette with a dropped shoulder. Each piece is uniquely textured.',
    price: 4299,
    images: [
      { url: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=1200&auto=format&fit=crop', publicId: 'p3', alt: 'Spectral Knit Artifact Main' },
      { url: 'https://images.unsplash.com/photo-1578932750294-f5075e85f44a?w=1200&auto=format&fit=crop', publicId: 'p3-2', alt: 'Spectral Knit Artifact Side' }
    ],
    category: 'winter',
    sizes: [{ size: 'M', stock: 6 }, { size: 'L', stock: 6 }],
    colors: [{ name: 'Spectral', hex: '#F0F0F0' }],
    totalStock: 12,
    featured: false,
    newArrival: true,
    viewCount: 890,
    soldCount: 23,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '4',
    name: 'Mono Fleece Artifact',
    slug: 'mono-fleece-artifact',
    brand: 'AXIS',
    description: 'Monochrome fleece pullover. High-density embroidery and custom metal hardware. Built for endurance.',
    price: 2899,
    images: [
      { url: 'https://images.unsplash.com/photo-1512353087810-25dfed2097df?w=1200&auto=format&fit=crop', publicId: 'p4', alt: 'Mono Fleece Artifact Main' },
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=1200&auto=format&fit=crop', publicId: 'p4-2', alt: 'Mono Fleece Artifact Fabric' }
    ],
    category: 'streetwear',
    sizes: [{ size: 'S', stock: 15 }, { size: 'M', stock: 20 }, { size: 'L', stock: 10 }],
    colors: [{ name: 'Shadow', hex: '#4A4A4A' }],
    totalStock: 45,
    featured: false,
    newArrival: false,
    viewCount: 1560,
    soldCount: 112,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '5',
    name: 'Cyber Artifact Hoodie',
    slug: 'cyber-artifact-hoodie',
    brand: 'AXIS',
    description: 'Neon-infused structural knit. Cyberpunk aesthetic with high-performance tech fabric.',
    price: 3999,
    images: [
      { url: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=1200', publicId: 'p5', alt: 'Cyber Artifact Hoodie' }
    ],
    category: 'streetwear',
    sizes: [{ size: 'M', stock: 10 }, { size: 'L', stock: 5 }],
    colors: [{ name: 'Neon', hex: '#39FF14' }],
    totalStock: 15,
    featured: true,
    newArrival: true,
    viewCount: 1500,
    soldCount: 30,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '6',
    name: 'Urban Ghost Hoodie',
    slug: 'urban-ghost-hoodie',
    brand: 'AXIS',
    description: 'Subtle gray tones with reflective details. Perfect for nighttime urban exploration.',
    price: 3599,
    images: [
      { url: 'https://images.unsplash.com/photo-1578932750294-f5075e85f44a?w=1200', publicId: 'p6', alt: 'Urban Ghost Hoodie' }
    ],
    category: 'oversized',
    sizes: [{ size: 'S', stock: 8 }, { size: 'M', stock: 12 }],
    colors: [{ name: 'Mist', hex: '#D3D3D3' }],
    totalStock: 20,
    featured: true,
    newArrival: false,
    viewCount: 1100,
    soldCount: 50,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '7',
    name: 'Stealth Tech Hoodie',
    slug: 'stealth-tech-hoodie',
    brand: 'AXIS',
    description: 'Water-resistant matte finish. Multiple hidden pockets and ergonomic silhouette.',
    price: 4599,
    images: [
      { url: 'https://images.unsplash.com/photo-1512353087810-25dfed2097df?w=1200', publicId: 'p7', alt: 'Stealth Tech Hoodie' }
    ],
    category: 'streetwear',
    sizes: [{ size: 'L', stock: 10 }, { size: 'XL', stock: 8 }],
    colors: [{ name: 'Matte Black', hex: '#2B2B2B' }],
    totalStock: 18,
    featured: true,
    newArrival: true,
    viewCount: 1800,
    soldCount: 40,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '8',
    name: 'Crimson Structure Hoodie',
    slug: 'crimson-structure-hoodie',
    brand: 'AXIS',
    description: 'Bold crimson red. Heavyweight fleece for maximum warmth and structure.',
    price: 3799,
    images: [
      { url: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=1200', publicId: 'p8', alt: 'Crimson Structure Hoodie' }
    ],
    category: 'winter',
    sizes: [{ size: 'M', stock: 15 }, { size: 'L', stock: 10 }],
    colors: [{ name: 'Crimson', hex: '#990000' }],
    totalStock: 25,
    featured: true,
    newArrival: false,
    viewCount: 950,
    soldCount: 60,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '9',
    name: 'Midnight Knit Hoodie',
    slug: 'midnight-knit-hoodie',
    brand: 'AXIS',
    description: 'Deep midnight blue. Hand-finished knit texture with an oversized fit.',
    price: 4199,
    images: [
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=1200', publicId: 'p9', alt: 'Midnight Knit Hoodie' }
    ],
    category: 'winter',
    sizes: [{ size: 'S', stock: 5 }, { size: 'M', stock: 10 }],
    colors: [{ name: 'Midnight', hex: '#191970' }],
    totalStock: 15,
    featured: true,
    newArrival: true,
    viewCount: 1300,
    soldCount: 25,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '10',
    name: 'Arctic Fleece Hoodie',
    slug: 'arctic-fleece-hoodie',
    brand: 'AXIS',
    description: 'Pure arctic white. Ultra-soft fleece lining for extreme comfort.',
    price: 3299,
    images: [
      { url: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=1200', publicId: 'p10', alt: 'Arctic Fleece Hoodie' }
    ],
    category: 'streetwear',
    sizes: [{ size: 'M', stock: 20 }, { size: 'L', stock: 15 }],
    colors: [{ name: 'Arctic White', hex: '#FFFFFF' }],
    totalStock: 35,
    featured: true,
    newArrival: false,
    viewCount: 2200,
    soldCount: 100,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '11',
    name: 'Desert Storm Hoodie',
    slug: 'desert-storm-hoodie',
    brand: 'AXIS',
    description: 'Earth-toned sand color. Distressed edges for a rugged, industrial look.',
    price: 3699,
    images: [
      { url: 'https://images.unsplash.com/photo-1578932750294-f5075e85f44a?w=1200', publicId: 'p11', alt: 'Desert Storm Hoodie' }
    ],
    category: 'oversized',
    sizes: [{ size: 'S', stock: 10 }, { size: 'M', stock: 10 }],
    colors: [{ name: 'Sand', hex: '#C2B280' }],
    totalStock: 20,
    featured: true,
    newArrival: true,
    viewCount: 1400,
    soldCount: 35,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '12',
    name: 'Forest Artifact Hoodie',
    slug: 'forest-artifact-hoodie',
    brand: 'AXIS',
    description: 'Deep forest green. Reinforced elbows and a heavy-duty double hood.',
    price: 3899,
    images: [
      { url: 'https://images.unsplash.com/photo-1512353087810-25dfed2097df?w=1200', publicId: 'p12', alt: 'Forest Artifact Hoodie' }
    ],
    category: 'winter',
    sizes: [{ size: 'L', stock: 12 }, { size: 'XL', stock: 8 }],
    colors: [{ name: 'Forest', hex: '#228B22' }],
    totalStock: 20,
    featured: true,
    newArrival: false,
    viewCount: 1600,
    soldCount: 45,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
